name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn set version 3.3.1
      - name: Install dependencies
        run: yarn install --immutable
      - name: Check types
        run: yarn tsc:check
      - name: Check eslint
        run: yarn eslint:check
      - name: Run tests
        run: yarn test
